export const CONTENT_MODES={concept:{name:'讲懂概念',description:'让小白理解一个概念或现象'},howto:{name:'照着操作',description:'交代入口、步骤和成功检查'},opinion:{name:'讨论观点',description:'用依据解释判断与适用范围'}};
export const defaultPreferences=()=>({revision:0,audience:'刚接触 AI、希望用工具解决问题的小白',tone:'像朋友讲解，短句，先解释陌生词',depth:'concept',visualDirection:'封面突出一个主题；内页少字、大字，用对照或图形解释。',personalCase:false});
const hash=x=>{let h=2166136261;for(const ch of JSON.stringify(x))h=Math.imul(h^ch.charCodeAt(0),16777619);return(h>>>0).toString(16);};
const text=(x,max=3000)=>typeof x==='string'&&x.length<=max;
export function validatePreferences(x){if(!x||!Number.isInteger(x.revision)||x.revision<0||!CONTENT_MODES[x.depth]||typeof x.personalCase!=='boolean'||!['audience','tone','visualDirection'].every(k=>text(x[k])))throw Error('账号偏好格式错误');return x;}
export function newPlanning(p,prefs=defaultPreferences()){return {idea:p.content.topic,mode:prefs.depth,audience:p.content.brief?.audience||prefs.audience,tone:prefs.tone,visualDirection:prefs.visualDirection,personalCase:prefs.personalCase,candidates:[],selectedId:null};}
export function planningOf(p,prefs){return p.planning||newPlanning(p,prefs);}
export function planningInputKey(x){return hash({idea:x.idea,mode:x.mode,audience:x.audience,tone:x.tone,visualDirection:x.visualDirection,personalCase:x.personalCase});}
export function validatePlanning(x){if(x===undefined)return;if(!x||!CONTENT_MODES[x.mode]||!['idea','audience','tone','visualDirection'].every(k=>text(x[k]))||typeof x.personalCase!=='boolean'||!Array.isArray(x.candidates)||x.candidates.length>6||!(x.selectedId===null||text(x.selectedId,80)))throw Error('选题策划格式错误');
 const ids=new Set();for(const c of x.candidates){if(!c||!text(c.id,80)||!c.id||ids.has(c.id)||!text(c.inputFingerprint,80)||!['title','audience','benefit','reason'].every(k=>text(c[k]))||!c.title.trim()||!c.benefit.trim()||!Array.isArray(c.outline)||!c.outline.length||c.outline.length>8||!c.outline.every(t=>text(t)&&t.trim())||!Array.isArray(c.evidence)||c.evidence.length>8||!c.evidence.every(t=>text(t)))throw Error('策划方向需要标题、读者收益、简短大纲和依据清单');ids.add(c.id);}
 if(x.selectedId&&!x.candidates.some(c=>c.id===x.selectedId&&c.inputFingerprint===planningInputKey(x)))throw Error('所选策划与当前输入不一致，请重新选择');
}
export function selectedPlan(p){const x=p.planning;if(!x)return null;return x.candidates.find(c=>c.id===x.selectedId&&c.inputFingerprint===planningInputKey(x))||null;}
export function importPlans(p,body,prefs,makeId){const x=structuredClone(planningOf(p,prefs));if(body.inputFingerprint!==planningInputKey(x))throw Error('策划输入已变化，请使用当前版本重新策划');if(!Array.isArray(body.candidates)||!body.candidates.length||body.candidates.length>6)throw Error('请导入1至6个策划方向');x.candidates=body.candidates.map(c=>({...c,id:makeId(),inputFingerprint:body.inputFingerprint}));x.selectedId=null;validatePlanning(x);p.planning=x;return p;}
export function applyPlan(p,id){const x=p.planning,c=x?.candidates.find(c=>c.id===id&&c.inputFingerprint===planningInputKey(x));if(!c)throw Error('策划方向不存在或输入已变化');x.selectedId=id;const old=p.content.brief||{audience:'',benefit:'',direction:'',references:[]};p.content.takeaway=c.benefit;p.content.brief={...old,audience:c.audience||x.audience,benefit:c.benefit,direction:[`内容方式：${CONTENT_MODES[x.mode].name}`,`选定标题：${c.title}`,`口吻：${x.tone}`,x.personalCase?'仅使用有事实依据的个人案例。':'通用讲解，不写创作者个人经历。',`大纲：${c.outline.join('；')}`,`依据或例子：${c.evidence.join('；')||'创作前核实必要事实'}`,`视觉偏好：${x.visualDirection}`].join('\n')};return p;}
export function planningTask(p,prefs,origin){const x=planningOf(p,prefs);return `请为工作台项目 ${p.id} 做选题策划。先读取 ${origin}/api/projects/${p.id}/planning-input，使用当时的 revision 和 inputFingerprint。想法：${x.idea}。方式：${CONTENT_MODES[x.mode].name}；受众：${x.audience}；口吻：${x.tone}；${x.personalCase?'个人案例仅在有真实材料时使用':'通用讲解，不关联创作者个人经历'}。提出3个切入角度不同的方向，每个提供 title、audience、benefit、reason（推荐理由）、outline（简短大纲数组）、evidence（需要核实的事实或例子数组）。核实关键事实，不虚构经历、效果或平台数据。先只策划，不写完整正文、不生成封面、不代替用户选择或审核。将 {revision,inputFingerprint,candidates:[...]} POST 到返回的 importEndpoint。输入或版本冲突时重新读取，不覆盖新修改；导入后提醒用户在策划页选择。工具不可用时返回同结构的 JSON，可在网页手动导入。`;}
