import {test} from 'node:test';
import assert from 'node:assert/strict';
import {defaultPreferences,newPlanning,planningInputKey,importPlans,applyPlan,validatePlanning,planningTask} from '../planning.mjs';
import {seedProject,contentKey,cardKey,validateProject} from '../model.mjs';
import {planningView} from '../dist/planning-ui.js';
const candidate={title:'代码搬了，照片怎么办？',audience:'第一次换电脑的人',benefit:'分清代码与资料',reason:'先解释区别',outline:['代码是什么','资料另存'],evidence:['GitHub 官方文档']};
test('策划输入绑定本期偏好；导入只保存方向，正文与审核指纹不变',()=>{const p=seedProject();p.planning=newPlanning(p);const text=contentKey(p),visual=cardKey(p),key=planningInputKey(p.planning);importPlans(p,{inputFingerprint:key,candidates:[candidate]},defaultPreferences(),()=> 'plan-1');assert.equal(contentKey(p),text);assert.equal(cardKey(p),visual);assert.equal(p.planning.selectedId,null);p.planning.personalCase=true;assert.notEqual(planningInputKey(p.planning),key);assert.throws(()=>applyPlan(p,'plan-1'),/输入已变化/);});
test('用户选择方向更新简报，保留既有图卡；缺失与过期方向不可选择',()=>{const p=seedProject(),cards=structuredClone(p.content.cards);p.planning=newPlanning(p);importPlans(p,{inputFingerprint:planningInputKey(p.planning),candidates:[candidate]},defaultPreferences(),()=> 'plan-1');applyPlan(p,'plan-1');assert.deepEqual(p.content.cards,cards);assert.equal(p.content.takeaway,candidate.benefit);assert.match(p.content.brief.direction,/通用讲解/);assert.match(p.content.brief.direction,/讲懂概念/);assert.doesNotThrow(()=>validateProject(p));p.planning.idea='新主题';assert.throws(()=>validatePlanning(p.planning),/不一致/);});
test('导入无大纲的策划拒绝且不改变旧方向；页面转义用户文本',()=>{const p=seedProject();p.planning=newPlanning(p);const prior=structuredClone(p.planning);assert.throws(()=>importPlans(p,{inputFingerprint:planningInputKey(p.planning),candidates:[{...candidate,outline:[]}]},defaultPreferences(),()=> 'x'),/大纲/);assert.deepEqual(p.planning,prior);importPlans(p,{inputFingerprint:planningInputKey(p.planning),candidates:[{...candidate,title:'<script>alert(1)</script>'}]},defaultPreferences(),()=> 'x');const html=planningView(p,defaultPreferences());assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));assert.match(planningTask(p,defaultPreferences(),'http://localhost:4318'),/不代替用户选择或审核/);});
